### ISSUE TITLE
How to send customized settings to Clarius App

### ISSUE THREAD

**Issue by pcanas** [clariusdev/mobileapi#21]
From the `me.clarius.mobileapi.SettingsInfo` class, it seems that we can modify the Clarius App settings at launch time. I was wondering:
1. Could you provide an example of how this class is being used to launch the Clarius App with a customized setting?
2. Are there any other parameters that are customizable besides the 7 defined?

**Comment by julien-l** [comment]
1. Create an instance of `SettingsInfo`, place it in a bundle under key `KEY_SETTINGS_INFO` then, send the bundle in a message with action code `MSG_SET_SETTINGS_INFO`, for example:

        public void sendSettings() {
            SettingsInfo info = new SettingsInfo();
            info.autoConnect = ...
            Message msg = Message.obtain(null, MobileApi. MSG_SET_SETTINGS_INFO);
            Bundle data = new Bundle();
            data.putParcelable(MobileApi.KEY_PATIENT_INFO, info);
            msg.setData(data);
            mService.send(msg);
        }

2. Only the settings listed in the class can be changed. These were selected because they can control the user workflow. If you wish control over more settings, you can make a request here + explanation why they are needed (this helps us evaluate requests) thanks!

**Comment by clariusk** [comment]
note our next release will solve: https://github.com/clariusdev/mobileapi/issues/18

**Comment by pcanas** [comment]
Thanks for your help!
@clariusk is there an expected timeline for the next release?

**Comment by clariusk** [comment]
please see the latest app pilot with latest code here to get fix for reported issue

**Comment by pcanas** [comment]
Was it released in the recent 9.3 version?
