### ISSUE TITLE
License not found

### ISSUE THREAD

**Issue by davidmatos** [clariusdev/mobileapi#4]
### Observed behaviour
Sometimes I get a "license not found" error. I couldn't reproduce this bug, so I don't know what's causing it. When this happens I have to quit everything and restart Clairus App before I start my app.

### Steps to reproduce
I know that one of the reasons that causes this issue is when the probe enters "sleep mode". But it also happens in other occasions. 

### Expected behaviour
The license verification should not fail arbitrarily

**Comment by julien-l** [comment]
The Mobile API license is linked to individual _scanners_, as opposed to user accounts, and is active only when a scanner is currently connected to the app. When your scanner goes to sleep, it disconnects and the license is removed. This is the expected behaviour as described in the README's licensing section  https://github.com/clariusdev/mobileapi#licensing.

The license is automatically re-activated as soon at the scanner re-connects and a notification message is sent to the Mobile API.
